baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ensono Stacks CLI"

theme = "book"

ignoreFiles = ['manual\.adoc', 'appendix\.adoc']

[[menu.Main]]
    name = "Usage"
    url = "/usage"
    weight = 50