import:
  - ./build/eirctl/contexts.yaml
  - ./build/eirctl/tasks.yaml

pipelines:
  build:
    - task: clean
    - task: buildnumber
    - task: _docs
      depends_on:
        - clean
        - buildnumber
    - task: test:unit
      depends_on: clean
    - task: _compile
      depends_on:
        - clean
        - buildnumber

  docs:
    - task: buildnumber
    - task: _docs:cmd:options
    - task: _docs
      depends_on:
        - buildnumber
        - _docs:cmd:options

  inttest:
    - task: buildnumber
    - task: test:int
      depends_on: buildnumber
    - task: test:int:generate_report
      depends_on: test:int

  compile:
    - task: buildnumber
    - task: _compile
      depends_on: buildnumber

  release:
    - task: buildnumber
    - task: _release
      depends_on:
        - buildnumber
