import:
  - ./build/eirctl/contexts.yaml
  - ./build/eirctl/tasks.yaml

pipelines:
  build:
    - task: clean
    - task: build:number
    - task: _docs
      depends_on:
        - clean
        - build:number
    - task: test:unit
      depends_on: clean
    - task: _compile
      depends_on:
        - clean
        - build:number

  docs:
    - task: build:number
    - task: _docs:cmd:options
    - task: _docs
      depends_on:
        - build:number
        - _docs:cmd:options

  inttest:
    - task: build:number
    - task: test:int
      depends_on: build:number
    - task: test:int:generate_report
      depends_on: test:int

  compile:
    - task: build:number
    - task: _compile
      depends_on: build:number

  release:
    - task: build:number
    - task: _release
      depends_on:
        - build:number
