=== Static values

To make updating easier the CLI utilises a feature in Go that allows text to be embedded into variable at build time. This means that the files are just ext files that do not have to be escaped within the Go code itself.

A number of items are embedded using this technique.

==== Azure DevOps Variable Template

The following listing shows the built in template that is used for the variable template if one is not set in the project settings file.

A new setting has been added to the internal configuration called `template_mode` which defaults to `true`. In this mode nothing changes and the template file will be written out to the project as usual. However if this is set to `false` then the internal static file is not written out and the CLI makes the necessary changes directly on the files based on the configuration in the `stackscli.yml` file in the project.

Location: `internal/config/staticFiles/ado_variable_template.yml`

.Azure DevOps Variable Template
[[azdo_variable_template,{listing-caption} {counter:refnum}]]
[source,yaml]
----
include::../../internal/config/staticFiles/ado_variable_template.yml[]
----

NOTE: This can be overriden on the command line, when using the `scaffold` command, with the `--adovariables` option to specify the path to the variables file to us.

==== Banner Text

The banner that is seen when the CLI runs is configured as a text file

Location: `internal/config/staticFiles/banner.txt`

.Banner text
[[banner_text,{listing-caption} {counter:refnum}]]
[source,txt]
----
include::../../internal/config/staticFiles/banner.txt[]
----

[#static_internal_config]
==== Internal Configuration

There are a number of settings that are hard hardcoded into the CLI. These include:

* Framework Definitions
** Each framework has a number of commands that need to exist on the machine in order to work. This is used to ensure that these programs are present.
** Version constraints on the tool being used
* Ensono Stacks Components
** Defines where the CLI can find the components for each of the different types of projects
** Allows different branches to be used for testing purposes
* Online Help
* Commands

All of these are defined in one file which is included at build time. The CLI now has the ability to look at files in a the users home directory in `.stackscli` and if a file called `internal_config.yml` file is found this will be read in and merged with the internal configuration.

Location: `internal/config/staticFiles/config.yml`

.Internal configuration
[[internal_config,{listing-caption} {counter:refnum}]]
[source,yaml]
----
include::../../internal/config/staticFiles/config.yml[]
----
