- name: dotnet
  commands:
    - dotnet
    - git
  version:
    command: dotnet
    arguments: --version
    pattern: (?P<version>.*)

- name: java
  commands:
    - java
    - git
    - mvn
  version:
    command: java
    arguments: -version
    pattern: '"(?P<version>.*)"'

- name: nx
  commands:
    - node
    - npx
    - git
  version:
    command: node
    arguments: --version
    pattern: '"v(?P<version>.*)"'

- name: infra
  commands:
    - git
