root: "https://stacks.amido.com/docs/stackscli/usage"
scaffold: "https://stacks.amido.com/docs/stackscli/runtime_config#scaffold-options"
interactive: "https://stacks.amido.com/docs/stackscli/runtime_config#interactive-options"
version: "https://stacks.amido.com/docs/stackscli/runtime_config#version-options"