==== Interactive Command

The interactive command will ask several questions about the required projects, what platform it is being run on and cloud configuration. It will then save the output of these details to a configuration file that can then be read in by the `scaffold` command. This file can also be reused if the projects need to be recreated from scratch again.

[source,bash]
----
stacks-cli interactive
----

The following table details the questions that will be asked and what they are used for.

.Initial Configuration Questions
[cols="2,2,1",options=header]
|===
| Question | Description | Example
| 
What is the name of your company?
| This is used to help name resources in the chosen cloud platform | Ensono

|
What is the scope or area of the project?
| As there can be many different projects being created within a team, this value is designed to be used to categorise the project | core

|
What component is being worked on?
| When using Ensono Stacks the scaffolded project is usually being created as part of a larger solution. This value is used to help name the project | backend

|
What pipeline is being used?
| A number of different pipelines can be configured to work with Ensono Stacks. Select the pipeline that this project will use. | azdo

|
Which cloud is Ensono Stacks being setup in?
| Ensono Stacks supports being deployed into different cloud platforms. Select the cloud that will be used. | azure

| 
Which group is the Terraform state being saved in?
| This is the group that contains the storage account for the Terraform state.
| `stacks-ancillary-resources` 

|
What is the name of the Terraform storage?
| The name of the Azure Storage account or S3 bucket being used to store the Terraform state | `lj9sadflkj9`

|
What is the name of the Terraform storage container?
| This is the container within the storage that the Terraform state is saved to | tfstate

|
What is the external domain of the solution?
| The domain that the projects will be accessible on. This needs to be a domain that is already registered and can be used. | stacks.ensono.com

| 
What is the internal domain of the solution?
| The internal domain of the application. If not specified this will be derived from the external domain.
So if `stacks.ensono.com` is used then the internal will be `stacks.ensono.internal` | stacks.ensono.internal

|
What options would you like to enable, if any?
| A selection of options that can be applied to the CLI.

* Command Log - list of all external commands that have been executed
* Dry Run - run the command without performing any of the tasks |

|
Please specify the working directory for the projects?
| All of the projects that are generated by the CLI will be stored in this directory in a folder based on the project name | Current Directory

| How many projects would you like to configure?
| The CLI is designed to be able to scaffold multiple projects at once. By providing the number of projects, you will be asked a series of questions for each project | 1
|===

[sidebar]
The questions in the following table will be asked as many times as the number of projects that have been specified. So if you have specified 3 projects, you will be asked these questions 3 times.

.Project Configuration Questions
[cols="2,2,1,1",options=header]
|===
| Question | Description | Applicable | Example
| 
What is the project name?
| The name of the project to created. | pre | docsAPI

|
What framework should be used for the project?
| The framework/language that the project should be based on. This is one of the following options

* .NET (dotnet)
* Java (java)
* NX (nx)
* Infrastructure (infra)

Subsequent questions that are asked will be dependent on the framework that is selected. | pre | dotnet

|
Which option of the framework do you require?
| Ensono Stacks has a number of options that are available for specific frameworks. Select the one that is appropriate for the desired workload.

* WebAPI (webapi) [.NET, Java]
* CQRS (cqrs) [.NET, Java]
* CQRS with Events [Java]
** For .NET this is included in the CQRS library | dotnet, java | webapi

|
Specify any additional framework properties. (Use a comma to separate each one).
| Additional properties that need to applied to the project when it is built.

This is dependent on the framework that has been chosen. Multiple options can be specified by separating the options with a comma | dotnet, java |

| 
Which type of infrastructure is required?
| A number of projects support different infrastructure. By answering this question, the CLI will prepare the project, if applicable, to the chosen cloud. 

* AKS
* Data

| infra | aks

|
Which version of the framework option do you require?
| There are a number of different versions of the frameworks that can be used. Specify the one that is required | post | latest

|
Please select the source control system being used?
| This is the centralised source control that should be used | post | github

|
What is the URL of the remote repository?
| When the project is scaffolded and configured as a Git repo, it will add in the `origin` to this URL. | post | https://github.com/ensono/stacks-cli

|
Which cloud region should be used?
| The region, of the chosen cloud, that the resources will be deployed to. Must be a valid Azure or AWS region name. | post | westeurope

|
What is the name of the group for all the resources?
| The name of the group into which all the resources for this project will be deployed into | post | dotnet-webapi


|===

Please see the <<.NET WebApi project using the interactive mode>> section for an example of how this command can be used.

The CLI allows properties to be set that influence the way that the project is scaffolded. Up to five of these properties can be set. However the interactive command only asks once if properties are required. To set more than property, please separate the values using a comma.
