==== Global Options

The following options can be applied to any command within the Ensono Stacks CLI.

.Global Options
include::tables/rootCmd.adoc[]

As the table above is generated by analysing the code, some of the default values are not computed as it is just test analysis. The following table shows what these values are.

[cols="1,1,2"]
|===
| Variable Name | Description | Example Value
| `defaultWorkingDir` | Where the CLI should work from. Defaults to the current directory | `/home/user/stacks/workspaces`
| `defaultTmpDir` | The path to the temp directory in the operating system | `/home/user/stacks/.config`
| `defaultUserHomeDir` | The home directory of the user running the command | `c:\Users\stacks`
|===

 [NOTE]
 .Global Parameters
 ====
 A number of parameters, that are shared between commands, are set as global parameters. The reason for this is the way that values are read in when they have the same name. If they have the same name and are not global then the program is not able to determine which value is required and could end up with unpredictable results. By making them global these parameters are shared between the commands and they do not overwrite each other.
 ====
