variables:
  - name: region
    value: {{ .Project.Cloud.Region }}
  - name: company
    value: {{ .Input.Business.Company }}
  - name: project
    value: {{ .Project.Name }}
  - name: domain
    value: {{ .Input.Business.Domain }}
  - name: self_repo
    value: {{ .Project.Name }}
  - name: self_generic_name
    value: $(company)-$(domain)

  # Terraform Configuration

  # State configuration

  # Stacks operates Terraform states based on workspaces **IT IS VERY IMPORTANT** that you ensure a unique name for each application definition
  # Furthermore **IT IS VERY IMPORTANT** that you change the name of a workspace for each deployment stage
  # there are some best practices around this if you are going for feature based environments
  # avoid running anything past dev that is not on master
  - name: tf_state_rg
    value: {{ .Input.Terraform.Backend.Group }}
  - name: tf_state_storage
    value: {{ .Input.Terraform.Backend.Storage }}
  - name: tf_state_container
    value: {{ .Input.Terraform.Backend.Container }}
  - name: tf_state_key
    value: $(self-generic-name)

  # TF Variables
  # --nonprod
  - name: tf_app_insights_name_nonprod
    value: ""
  - name: tf_app_gateway_frontend_ip_name_nonprod
    value: ""
  - name: tf_core_resource_group_nonprod
    value: ""

  # --prod
  - name: tf_app_insights_name_prod
    value: ""
  - name: tf_app_gateway_frontend_ip_name_prod
    value: ""
  - name: tf_core_resource_group_prod
    value: ""

  # Kubernetes configuration
  # --nonprod
  - name: kubernetes_clusterrg_nonprod
    value: ""
  - name: kubernetes_clustername_nonprod
    value: ""

  # --prod
  - name: kubernetes_clusterrg_prod
    value: ""
  - name: kubernetes_clustername_prod
    value: ""

  # Container registry information
  - name: docker_container_registry_name_nonprod
    value: ""
  - name: docker_container_registry_name_prod
    value: ""

  # Domain names
  - name: base_domain_nonprod
    value: nonprod.{{ .Input.Network.Base.Domain.External }}
  - name: base_domain_internal_nonprod
    value: nonprod.{{ .Input.Network.Base.Domain.Internal }}
  - name: base_domain_prod
    value: prod.{{ .Input.Network.Base.Domain.External }}
  - name: base_domain_internal_prod
    value: prod.{{ .Input.Network.Base.Domain.Internal }}

  # Environment
  # Set the name of the resource group that has the DNS zones to be updated
  - name: dns_zone_resource_group
    value:

  # GitHub infomration
  - name: create_release
    value: ""
  - name: github_release_service_connection
    value: ""
  - name: github_org
    value: $(company)

  # Azure service connection
  - name: azure_service_connection
    value: ""
