frameworks:
  - name: dotnet
    commands:
      - name: dotnet
        version:
          arguments: --version
          pattern: (?P<version>(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<feature>[0-9]{1})(?P<patch>[0-9]*))
      - name: git

  - name: java
    commands:
      - name: java
        version:
          arguments: -version
          pattern: version\s+"(?P<version>(?P<major>[0-9]*)\.(?P<minor>[0-9]*).(?P<patch>[0-9]*))
      - name: git
      - name: mvn

  - name: nx
    commands:
      - name: node
        version:
          arguments: -version
          pattern: v(?P<version>(?P<major>[0-9]*)\.(?P<minor>[0-9]*).(?P<patch>[0-9]*))
      - name: npx
      - name: git

  - name: infra
    commands:
      - name: git
      - name: terraform

stacks:
  components:
    dotnet_webapi:
      group: dotnet
      name: webapi
      package:
        name: Ensono.Stacks.Templates
        type: nuget
        id: stacks-dotnet

    dotnet_cqrs:
      group: dotnet
      name: cqrs
      package:
        name: Ensono.Stacks.Templates
        type: nuget
        id: stacks-dotnet

    java_webapi:
      group: java
      name: webapi
      package:
        url: https://github.com/Ensono/stacks-java
        version: master
        type: git

    java_cqrs:
      group: java
      name: cqrs
      package:
        url: https://github.com/Ensono/stacks-java-cqrs
        version: main
        type: git

    java_events:
      group: java
      name: events
      package:
        url: https://github.com/Ensono/stacks-java-cqrs-events
        version: main
        type: git

    nx_next:
      group: nx
      name: next
      package:
        url: https://github.com/Ensono/stacks-nx
        version: main
        type: git

    nx_apps:
      group: nx
      name: apps
      package:
        url: https://github.com/Ensono/stacks-nx
        version: main
        type: git

    infra_aks:
      group: infra
      name: aks
      package:
        url: https://github.com/Ensono/stacks-infrastructure-aks/
        version: master
        type: git

    infra_data:
      group: infra
      name: data
      package:
        url: https://github.com/Ensono/stacks-azure-data
        version: main
        type: git
    
    infra_aca:
      group: infra
      name: aca
      package:
        url: https://github.com/Ensono/stacks-infrastructure-aca/
        version: main
        type: git

    infra_template:
      group: infra
      name: template
      package:
        url: https://github.com/Ensono/stacks-project-template
        version: main
        type: git

help:
  root: "https://stacks.ensono.com/docs/stackscli/usage"
  scaffold: "https://stacks.ensono.com/docs/stackscli/runtime_config#scaffold-options"
  interactive: "https://stacks.ensono.com/docs/stackscli/runtime_config#interactive-options"
  version: "https://stacks.ensono.com/docs/stackscli/runtime_config#version-options"
  export: "https://stacks.ensono.com/docs/stackscli/runtime_config#export-options"

commands:
  git:
    - git init
    - git remote add origin {{ .Project.SourceControl.URL }}
