=== Static values

To make updating easier the CLI utilises a feature in Go that allows text to be embedded into variable at build time. This means that the files are just ext files that do not have to be escaped within the Go code itself.

A number of items are embedded using this technique.

==== Azure DevOps Variable Template

The following listing shows the built in template that is used for the variable template if one is not set in the project settings file.

Location: `internal/config/staticFiles/ado_veriable_template.yml`

.Azure DevOps Variable Template
[[azdo_variable_template,{listing-caption} {counter:refnum}]]
[source,yaml,subs="attributes"]
----
include::../internal/config/staticFiles/ado_variable_template.yml[]
----

NOTE: This can be overriden on the command line, when using the `scaffold` command, with the `--adovariables` option to specify the path to the variables file to us.

==== Banner Text

The banner that is seen when the CLI runs is configured as a text file

Location: `internal/config/staticFiles/banner.txt`

.Banner text
[[banner_text,{listing-caption} {counter:refnum}]]
[source,txt,subs="attributes"]
----
include::../internal/config/staticFiles/banner.txt[]
----

==== Internal Configuration

There are a number of settings that are hard hardcoded into the CLI. These include:

* Framework Definitions
** Each framework has a number of commands that need to exist on the machine in order to work. This is used to ensure that these programs are present.
** Version constraints on the tool being used
* Ensono Stacks Components
** Defines where the CLI can find the components for each of the different types of projects
** Allows different branches to be used for testing purposes
* Online Help
* Commands

All of these are defined in one file which is included at build time. However all of the values can be overridden at run time using the `--internalconfig` argument.

Location: `internal/config/staticFiles/config.yml`

.Internal configuration
[[internal_config,{listing-caption} {counter:refnum}]]
[source,yaml,subs="attributes"]
++++
include::../internal/config/staticFiles/config.yml[]
++++

=== Exit Codes

The following table shows the exit codes that the CLI will emit on an error.

[options="header",cols="1,5"]
|===
| Exit Code | Description
| 1 | Unable to read in the internal configuration. If this occurs then there is an issue with the published CLI
| 2 | Occurs when the CLI is not able to read in the override file for the internal configuration
| 3 | When using the `scaffold` command and the Azure DevOps file has been specified and it cannot be read in
| 4 | After all the parsing of the command line options and arguments, it cannot be read properly
|===