:listing-caption: Listing

== Project Settings

Each project that is supported by the Stacks CLI have a settings file associated with them. This is called, by default, `stackscli.yml`. It is possible to override the actual file that is used as well as the filename.

The settings file is intended to allow the project maintainers to define what steps needs to be done on a project and instruct the CLI what to do, without having to refactor the CLI.

=== Structure

The following table details the structure of the settings file.

.Settings file root structure
[options="header"]
|===
| Parameter | Description | Example | Allowed Values 
| `framework` | The framework that the project is based on. | `dotnet` | `dotnet`, `java`, `node` 
| `pipeline` | This is a list of the supported pipelines and the associated files | |
| `init.operations` | List of operations that need to be performed on the temporary project directory | | 
| `setup.operations` | List of operations that need to be performed on the project directory | |
|===

The next table shows the options for the operations.

NOTE: These are valid for both `init` and `setup` operations

.Operations parameters
[options="header"]
|===
| Parameter | Description | Example | Allowed Values
| `action` | The type of action that needs to be performed | `cmd` | `cmd`, `copy` 
| `cmd` | The command that needs to be run.

Each framework has a set of commands that it knows it can during the setup of the project run. The value that is set here must be specified within that list in order for the command to execute. | java = `java`

dotnet = `dotnet` | 
| `args` | The arguments that need to be passed to the command | `new -i .` | 
| `desc` | Description of what is being performed. This is output during the execution of the CLI | Installing template from folder | 
|===

The follow table shows the values that can be assigned to the pipeline list.

.Pipeline options
[options="header"]
|===
| Parameter | Description | Example | Allowed Values
| `type` | Type of pipeline being configured | `azdo` | `azdo`
| `files` | List of files that should be worked on.

See <<project_settings_file_definition,File definition>> for syntax |  | 
| `template` | List of templates that the CLI should use. At the moment only `variable` is supported. |  | 
| `replacements` | This is a list of replacements that need to be made in the build file | | 
|===

.File definition
[[project_settings_file_definition]]
[options="header"]
|===
| Parameter | Description | Example
| `name` | Name of the file.

The names `build` and `variable` are reserved by the CLI and are used when writing out files.
Other files can be specified and the replacements will be made on each one.

The names must be unique, if not then the last one specified with the same name will take precedence. | `build`
| `path` | Path to the file in question, relative to the repository root | `build/azDevOps/azure/azure-pipelines-netcore-k8s.yml`
| `noreplace` | If set to `true` then no replacements will be attempted on this file.

This is not supported when used in a `template` definition. | `true`
|===

NOTE: If no template is specified for the `variable` then the static version built into the CLI will be used. This can be seen in <<azdo_variable_template>>.

.Replacement definition
[options="header"]
|===
| Parameter | Description | Example 
| `pattern` | Regular expression pattern for finding the text to be replaced | `^.*myvalue$`
| `value` | Value to replace the phrase that has been found by the pattern | `Foo Bar`
|===

=== YAML File

The following code listing shows an example settings file.

.Example project settings file
[[project_settings_file,{listing-caption} {counter:refnum}]]
[source,yaml]
----
framework: dotnet // <1>

pipeline:
  - type: azdo //<2>
    files:
       - name: build // <3>
         path: build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
       - name: variable // <4>
         path: build/azDevOps/azure/azuredevops-vars.yml 
    replacements: // <5>
        - pattern: ^.*myvalue$ 
          value: Foo Bar

init: // <6>
  operations: // <7>
    - action: cmd // <8>
      args: new stacks-docs -n {{ .Input.Business.Company }}.{{ .Input.Business.Domain }} // <9>
      desc: Create a project using the "stacks-docs" project // <10>

setup: // <11>
   operations:
----

<1> Sets the framework that the commands should be run for
<2> Specify the pipeline that is being targeted
<3> Name and path to the build pipeline file in the repository, for the specified pipeline system
<4> Name and path to the variable template in the repository
<5> List of replacements that should be made in the specified build file
<6> Perform operations on the temporary project directory
<7> List any number of operations that need to be performed
<8> States the action that needs to be performed
<9> The arguments that need to be passed to the framework command, in this case `dotnet`
<10> Description of the operation, this will be displayed in the log output when the CLI is executed
<11> Define operations that need to be performed after the project has been created

This example shows one action that needs to be performed on the project before it has been created in the user specified working directory.

