:listing-caption: Listing

== Project Settings

Each project that is supported by the Stacks CLI have a settings file associated with them. This is called, by default, `stackscli.yml`. It is possible to override the actual file that is used as well as the filename.

The settings file is intended to allow the project maintainers to define what steps needs to be done on a project and instruct the CLI what to do, without having to refactor the CLI.

=== Structure

The following table details the structure of the settings file.

.Settings file root structure
[options="header"]
|===
| Parameter | Description | Example | Allowed Values 
| `framework` | The framework that the project is based on. | `dotnet` | `dotnet`, `java`, `node`
| `pipeline` | This is a list of the supported pipelines and the associated files | | |
| `init.operations` | List of operations that need to be performed on the temporary project directory | |
| `setup.operations` | List of operations that need to be performed on the project directory | |
|===

The next table shows the options for the operations.

NOTE: These are valid for both `init` and `setup` operations

.Operations parameters
[options="header"]
|===
| Parameter | Description | Example | Allowed Values
| `action` | The type of action that needs to be performed | `cmd` | `cmd`, `copy` 
| `cmd` | The command that needs to be run.

This is determined by the `framework` option in this file, which the CLI uses to determine the command to run. This setting can be used to override this value. | | 
| `args` | The arguments that need to be passed to the command | `new -i .` | 
| `desc` | Description of what is being performed. This is output during the execution of the CLI | Installing template from folder | 
|===

IMPORTANT: Care must be taken when changing the `cmd` from the default value. The CLI will check for the `dotnet`, `java` and NodeJS commands, but it will not check for commands that have been specified here. There is no way to guarantee that it is installed on the machine.

The follow table shows the values that can be assigned to the pipeline list.

.Pipeline options
[options="header"]
|===
| Parameter | Description | Example | Allowed Values
| `type` | Type of pipeline being configured | `azdo` | `azdo`
| `files.build` | Relative path to the main build file | `build/azDevOps/azure/azure-pipelines-netcore-k8s.yml` | 
| `files.variable` | Relative path to the variable file for the specified pipeline. This is where the CLI will write the file out to | `build/azDevOps/azure/azuredevops-vars.yml` | 
| `templates.variable` | Relative path to the template file to for the variable template.

If not set then the built in value for the template will be used. This template can be viewed in this listing <<azdo_variable_template>>. | |
| `replacements` | This is a list of replacements that need to be made in the build file | | 
|===

.Replacement definition
[options="header"]
|===
| Parameter | Description | Example 
| `pattern` | Regular expression pattern for finding the text to be replaced | `^.*myvalue$`
| `value` | Value to replace the phrase that has been found by the pattern | `Foo Bar`
|===

=== YAML File

The following code listing shows an example settings file.

.Example project settings file
[[project_settings_file,{listing-caption} {counter:refnum}]]
[source,yaml]
----
framework: dotnet // <1>

pipeline:
  - type: azdo //<2>
    files:
       build: build/azDevOps/azure/azure-pipelines-netcore-k8s.yml // <3>
       variable: build/azDevOps/azure/azuredevops-vars.yml // <4>
    replacements: // <5>
        - pattern: ^.*myvalue$ 
          value: Foo Bar

init: // <6>
  operations: // <7>
    - action: cmd // <8>
      args: new stacks-docs -n {{ .Input.Business.Company }}.{{ .Input.Business.Domain }} // <9>
      desc: Create a project using the "stacks-docs" project // <10>

setup: // <11>
   operations:
----

<1> Sets the framework that the commands should be run for
<2> Specify the pipeline that is being targeted
<3> Path to the build pipeline file in the repository, for the specified pipeline system
<4> Path to the variable template in the repository
<5> List of replacements that should be made in the specified build file
<6> Perform operations on the temporary project directory
<7> List any number of operations that need to be performed
<8> States the action that needs to be performed
<9> The arguments that need to be passed to the framework command, in this case `dotnet`
<10> Description of the operation, this will be displayed in the log output when the CLI is executed
<11> Define operations that need to be performed after the project has been created

This example shows one action that needs to be performed on the project before it has been created in the user specified working directory.

