== Runtime Configuration

Configuration for the CLI can be performed in several ways:

  - On the command line
  - Using environment variables
  - Using a configuration file (YAML or JSON)

When using a configuration file it is possible to setup more than one project.

=== Settings

The following tables show the configuration options that are available at the root level and the command level.

include::runtime_config/global_options.adoc[]

include::runtime_config/completion_options.adoc[]

include::runtime_config/interactive_options.adoc[]

include::runtime_config/setup_options.adoc[]

include::runtime_config/scaffold_options.adoc[]

include::runtime_config/export_options.adoc[]

include::runtime_config/version_options.adoc[]

=== Command Log Format

If the command log has been enabled, using `--cmdlog`, a file with all the commands that have been run during the scaffolding operation will be generated. The format of this file is as follows:

`[<DIR>] <CMD> <ARGS>`

The <DIR> shows in which directory the command has been run in. Please note that this directory may have been deleted after the CLI has been run as it was temporary.

The <CMD> and <ARGS> show the command that was run and the arguments that were passed to it.

NOTE: On Windows based machines the <CMD> will be prefixed with `cmd /C` which tells the CLI how to run the command. PowerShell has not yet been used as it is easy to customise the shell and those customisations may cause the CLI to fail when running the commands.

=== Configuration File

The following shows an example of a configuration file that can be passed to the command.

.CLI Configuration File
[[cli_configuration_file,{listing-caption} {counter:refum}]]
[source,yaml]
----
project:
- name: tigerfest
  framework:
    option: webapi
    version: latest
  platform:
    type: aks    
  sourcecontrol:
    type: github
    url: https://github.com/russellseymour/my-new-project.git

pipeline: azdo

cloud:
  platform: azure
  region: ukwest
  group: a-new-resource-group

business:
  company: MyCompany
  domain: core
  component: infra

terraform:
  backend:
    storage: adfsdafsdfsdf
    group: Stacks-Ancillary-Resources
    container: tfstate

network:
  base:
    domain: 
      external: mydomain.com

log:
  level: info

options:
  cmdlog: false

stacks:
  dotnet:
    webapi: 
      url: https://github.com/Ensono/stacks-dotnet
      trunk: master
----

Note that when using the configuration file it is possible to specify multiple projects to be configured. This allows several projects to be setup at the same time, without having to run the command multiple times. Each project will be created within the specified working directory.

If this file was called `conf.yml` the command to run to consume the file would be:

[source,bash]
----
.\stacks-cli.exe scaffold -c .\local\conf.yml
----